SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

-- --------------------------------------------------------

--
-- Table structure for table `country_list`
--

DROP TABLE IF EXISTS `country_list`;
CREATE TABLE IF NOT EXISTS `country_list` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `COUNTRY_NAME` varchar(255) NOT NULL DEFAULT '',
  `COUNTRY_CODE` varchar(4) NOT NULL DEFAULT '',
  `POSTAL_CODE_REGEX` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=194 ;

--
-- Dumping data for table `country_list`
--

INSERT INTO `country_list` (`id`, `COUNTRY_NAME`, `COUNTRY_CODE`, `POSTAL_CODE_REGEX`) VALUES
(1, 'Afghanistan', 'AF', NULL),
(2, 'Albania', 'AL', NULL),
(3, 'Algeria', 'DZ', '/\\d{5}/i'),
(4, 'Andorra', 'AD', '/AD\\d{3}/i'),
(5, 'Angola', 'AO', NULL),
(6, 'Antigua and Barbuda', 'AG', NULL),
(7, 'Argentina', 'AR', '/([A-HJ-NP-Z])?\\d{4}([A-Z]{3})?/i'),
(8, 'Armenia', 'AM', '/(37)?\\d{4}/i'),
(9, 'Australia', 'AU', '/\\d{4}/i'),
(10, 'Austria', 'AT', '/\\d{4}/i'),
(11, 'Azerbaijan', 'AZ', '/\\d{4}/i'),
(12, 'Bahamas', 'BS', NULL),
(13, 'Bahrain', 'BH', '/((1[0-2]|[2-9])\\d{2})?/i'),
(14, 'Bangladesh', 'BD', '/\\d{4}/i'),
(15, 'Barbados', 'BB', '/(BB\\d{5})?/i'),
(16, 'Belarus', 'BY', '/\\d{6}/i'),
(17, 'Belgium', 'BE', '/\\d{4}/i'),
(18, 'Belize', 'BZ', NULL),
(19, 'Benin', 'BJ', NULL),
(20, 'Bhutan', 'BT', NULL),
(21, 'Bolivia', 'BO', NULL),
(22, 'Bosnia and Herzegovina', 'BA', '/\\d{5}/i'),
(23, 'Botswana', 'BW', NULL),
(24, 'Brazil', 'BR', '/\\d{5}[\\-]?\\d{3}/i'),
(25, 'Brunei', 'BN', '/[A-Z]{2}[ ]?\\d{4}/i'),
(26, 'Bulgaria', 'BG', '/\\d{4}/i'),
(27, 'Burkina Faso', 'BF', NULL),
(28, 'Burundi', 'BI', NULL),
(29, 'Cambodia', 'KH', '/\\d{5}/i'),
(30, 'Cameroon', 'CM', NULL),
(31, 'Canada', 'CA', '/[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z][ ]?\\d[ABCEGHJ-NPRSTV-Z]\\d/i'),
(32, 'Cape Verde', 'CV', '/\\d{4}/i'),
(33, 'Central African Republic', 'CF', NULL),
(34, 'Chad', 'TD', NULL),
(35, 'Chile', 'CL', '/\\d{7}/i'),
(36, 'China', 'CN', '/\\d{6}/i'),
(37, 'Colombia', 'CO', NULL),
(38, 'Comoros', 'KM', NULL),
(39, 'Congo', 'CD', NULL),
(40, 'Congo', 'CG', NULL),
(41, 'Costa Rica', 'CR', '/\\d{4,5}|\\d{3}-\\d{4}/i'),
(42, 'Cote d''Ivoire (Ivory Coast)', 'CI', NULL),
(43, 'Croatia', 'HR', '/\\d{5}/i'),
(44, 'Cuba', 'CU', NULL),
(45, 'Cyprus', 'CY', '/\\d{4}/i'),
(46, 'Czech Republic', 'CZ', '/\\d{3}[ ]?\\d{2}/i'),
(47, 'Denmark', 'DK', '/\\d{4}/i'),
(48, 'Djibouti', 'DJ', NULL),
(49, 'Dominica', 'DM', NULL),
(50, 'Dominican Republic', 'DO', '/\\d{5}/i'),
(51, 'Ecuador', 'EC', '/([A-Z]\\d{4}[A-Z]|(?:[A-Z]{2})?\\d{6})?/i'),
(52, 'Egypt', 'EG', '/\\d{5}/i'),
(53, 'El Salvador', 'SV', NULL),
(54, 'Equatorial Guinea', 'GQ', NULL),
(55, 'Eritrea', 'ER', NULL),
(56, 'Estonia', 'EE', '/\\d{5}/i'),
(57, 'Ethiopia', 'ET', '/\\d{4}/i'),
(58, 'Fiji', 'FJ', NULL),
(59, 'Finland', 'FI', '/\\d{5}/i'),
(60, 'France', 'FR', '/\\d{2}[ ]?\\d{3}/i'),
(61, 'Gabon', 'GA', NULL),
(62, 'Gambia', 'GM', NULL),
(63, 'Georgia', 'GE', '/\\d{4}/i'),
(64, 'Germany', 'DE', '/\\d{5}/i'),
(65, 'Ghana', 'GH', NULL),
(66, 'Greece', 'GR', '/\\d{3}[ ]?\\d{2}/i'),
(67, 'Grenada', 'GD', NULL),
(68, 'Guatemala', 'GT', '/\\d{5}/i'),
(69, 'Guinea', 'GN', '/\\d{3}/i'),
(70, 'Guinea-Bissau', 'GW', '/\\d{4}/i'),
(71, 'Guyana', 'GY', NULL),
(72, 'Haiti', 'HT', '/\\d{4}/i'),
(73, 'Honduras', 'HN', '/(?:\\d{5})?/i'),
(74, 'Hungary', 'HU', '/\\d{4}/i'),
(75, 'Iceland', 'IS', '/\\d{3}/i'),
(76, 'India', 'IN', '/\\d{6}/i'),
(77, 'Indonesia', 'ID', '/\\d{5}/i'),
(78, 'Iran', 'IR', NULL),
(79, 'Iraq', 'IQ', '/\\d{5}/i'),
(80, 'Ireland', 'IE', NULL),
(81, 'Israel', 'IL', '/\\d{5}/i'),
(82, 'Italy', 'IT', '/\\d{5}/i'),
(83, 'Jamaica', 'JM', NULL),
(84, 'Japan', 'JP', '/\\d{3}-\\d{4}/i'),
(85, 'Jordan', 'JO', '/\\d{5}/i'),
(86, 'Kazakhstan', 'KZ', '/\\d{6}/i'),
(87, 'Kenya', 'KE', '/\\d{5}/i'),
(88, 'Kiribati', 'KI', NULL),
(89, 'Korea', 'KP', NULL),
(90, 'Korea', 'KR', '/\\d{3}[\\-]\\d{3}/i'),
(91, 'Kuwait', 'KW', '/\\d{5}/i'),
(92, 'Kyrgyzstan', 'KG', '/\\d{6}/i'),
(93, 'Laos', 'LA', '/\\d{5}/i'),
(94, 'Latvia', 'LV', '/\\d{4}/i'),
(95, 'Lebanon', 'LB', '/(\\d{4}([ ]?\\d{4})?)?/i'),
(96, 'Lesotho', 'LS', '/\\d{3}/i'),
(97, 'Liberia', 'LR', '/\\d{4}/i'),
(98, 'Libya', 'LY', NULL),
(99, 'Liechtenstein', 'LI', '/(948[5-9])|(949[0-7])/i'),
(100, 'Lithuania', 'LT', '/\\d{5}/i'),
(101, 'Luxembourg', 'LU', '/\\d{4}/i'),
(102, 'Macedonia', 'MK', '/\\d{4}/i'),
(103, 'Madagascar', 'MG', '/\\d{3}/i'),
(104, 'Malawi', 'MW', NULL),
(105, 'Malaysia', 'MY', '/\\d{5}/i'),
(106, 'Maldives', 'MV', '/\\d{5}/i'),
(107, 'Mali', 'ML', NULL),
(108, 'Malta', 'MT', '/[A-Z]{3}[ ]?\\d{2,4}/i'),
(109, 'Marshall Islands', 'MH', '/969[67]\\d([ \\-]\\d{4})?/i'),
(110, 'Mauritania', 'MR', NULL),
(111, 'Mauritius', 'MU', '/(\\d{3}[A-Z]{2}\\d{3})?/i'),
(112, 'Mexico', 'MX', '/\\d{5}/i'),
(113, 'Micronesia', 'FM', '/(9694[1-4])([ \\-]\\d{4})?/i'),
(114, 'Moldova', 'MD', '/\\d{4}/i'),
(115, 'Monaco', 'MC', '/980\\d{2}/i'),
(116, 'Mongolia', 'MN', '/\\d{6}/i'),
(117, 'Montenegro', 'ME', '/8\\d{4}/i'),
(118, 'Morocco', 'MA', '/\\d{5}/i'),
(119, 'Mozambique', 'MZ', NULL),
(120, 'Myanmar (Burma)', 'MM', NULL),
(121, 'Namibia', 'NA', NULL),
(122, 'Nauru', 'NR', NULL),
(123, 'Nepal', 'NP', '/\\d{5}/i'),
(124, 'Netherlands', 'NL', '/\\d{4}[ ]?[A-Z]{2}/i'),
(125, 'New Zealand', 'NZ', '/\\d{4}/i'),
(126, 'Nicaragua', 'NI', '/((\\d{4}-)?\\d{3}-\\d{3}(-\\d{1})?)?/i'),
(127, 'Niger', 'NE', '/\\d{4}/i'),
(128, 'Nigeria', 'NG', '/(\\d{6})?/i'),
(129, 'Norway', 'NO', '/\\d{4}/i'),
(130, 'Oman', 'OM', '/(PC )?\\d{3}/i'),
(131, 'Pakistan', 'PK', '/\\d{5}/i'),
(132, 'Palau', 'PW', '/96940/i'),
(133, 'Panama', 'PA', NULL),
(134, 'Papua New Guinea', 'PG', '/\\d{3}/i'),
(135, 'Paraguay', 'PY', '/\\d{4}/i'),
(136, 'Peru', 'PE', NULL),
(137, 'Philippines', 'PH', '/\\d{4}/i'),
(138, 'Poland', 'PL', '/\\d{2}-\\d{3}/i'),
(139, 'Portugal', 'PT', '/\\d{4}([\\-]\\d{3})?/i'),
(140, 'Qatar', 'QA', NULL),
(141, 'Romania', 'RO', '/\\d{6}/i'),
(142, 'Russia', 'RU', '/\\d{6}/i'),
(143, 'Rwanda', 'RW', NULL),
(144, 'Saint Kitts and Nevis', 'KN', NULL),
(145, 'Saint Lucia', 'LC', NULL),
(146, 'Saint Vincent and the Grenadines', 'VC', NULL),
(147, 'Samoa', 'WS', NULL),
(148, 'San Marino', 'SM', '/4789\\d/i'),
(149, 'Sao Tome and Principe', 'ST', NULL),
(150, 'Saudi Arabia', 'SA', '/\\d{5}/i'),
(151, 'Senegal', 'SN', '/\\d{5}/i'),
(152, 'Serbia', 'RS', '/\\d{6}/i'),
(153, 'Seychelles', 'SC', NULL),
(154, 'Sierra Leone', 'SL', NULL),
(155, 'Singapore', 'SG', '/\\d{6}/i'),
(156, 'Slovakia', 'SK', '/\\d{3}[ ]?\\d{2}/i'),
(157, 'Slovenia', 'SI', '/\\d{4}/i'),
(158, 'Solomon Islands', 'SB', NULL),
(159, 'Somalia', 'SO', '/\\d{5}/i'),
(160, 'South Africa', 'ZA', '/\\d{4}/i'),
(161, 'Spain', 'ES', '/\\d{5}/i'),
(162, 'Sri Lanka', 'LK', '/\\d{5}/i'),
(163, 'Sudan', 'SD', NULL),
(164, 'Suriname', 'SR', NULL),
(165, 'Swaziland', 'SZ', '/[HLMS]\\d{3}/i'),
(166, 'Sweden', 'SE', '/\\d{3}[ ]?\\d{2}/i'),
(167, 'Switzerland', 'CH', '/\\d{4}/i'),
(168, 'Syria', 'SY', NULL),
(169, 'Tajikistan', 'TJ', '/\\d{6}/i'),
(170, 'Tanzania', 'TZ', NULL),
(171, 'Thailand', 'TH', '/\\d{5}/i'),
(172, 'Timor-Leste (East Timor)', 'TL', NULL),
(173, 'Togo', 'TG', NULL),
(174, 'Tonga', 'TO', NULL),
(175, 'Trinidad and Tobago', 'TT', NULL),
(176, 'Tunisia', 'TN', '/\\d{4}/i'),
(177, 'Turkey', 'TR', '/\\d{5}/i'),
(178, 'Turkmenistan', 'TM', '/\\d{6}/i'),
(179, 'Tuvalu', 'TV', NULL),
(180, 'Uganda', 'UG', NULL),
(181, 'Ukraine', 'UA', '/\\d{5}/i'),
(182, 'United Arab Emirates', 'AE', NULL),
(183, 'United Kingdom', 'GB', '/GIR[ ]?0AA|((AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}))|BFPO[ ]?\\d{1,4}/i'),
(184, 'United States', 'US', '/\\d{5}([ \\-]\\d{4})?/i'),
(185, 'Uruguay', 'UY', '/\\d{5}/i'),
(186, 'Uzbekistan', 'UZ', '/\\d{6}/i'),
(187, 'Vanuatu', 'VU', NULL),
(188, 'Vatican City', 'VA', '/00120/i'),
(189, 'Venezuela', 'VE', '/\\d{4}/i'),
(190, 'Vietnam', 'VN', NULL),
(191, 'Yemen', 'YE', NULL),
(192, 'Zambia', 'ZM', '/\\d{5}/i'),
(193, 'Zimbabwe', 'ZW', NULL);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
